import Config

# Configure your database
config :new_api_app, NewApiApp.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "new_api_app_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :new_api_app, NewApiAppWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "<<SECRET_KEY_BASE>>",
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :new_api_app, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Configure the Valkey (Redis-protocol) KV sidecar. Same host/port
# compose.yaml's valkey service publishes.
config :new_api_app, NewApiApp.Valkey.Cache.L1,
  gc_interval: :timer.hours(1),
  max_size: 1_000_000,
  allocated_memory: 100_000_000

config :new_api_app, NewApiApp.Valkey.Cache.L2,
  conn_opts: [
    host: System.get_env("VALKEY_HOST", "localhost"),
    port: String.to_integer(System.get_env("VALKEY_PORT", "6379"))
  ],
  pool_size: 5

config :new_api_app, NewApiApp.Valkey.Breaker,
  timeout_ms: 100,
  failure_threshold: 3,
  cooldown_ms: :timer.seconds(30)

config :new_api_app, NewApiApp.Valkey.Cache, default_ttl: :timer.minutes(10)
