%{
  aliases: [
    setup: ["\"deps.get\"", "\"ecto.setup\"", "\"assets.setup\""],
    "assets.setup": ["\"cmd --cd assets pnpm install\""],
    "assets.build": ["\"cmd --cd assets pnpm exec vite build\""],
    "assets.deploy": ["\"assets.build\""],
    "assets.check": ["\"assets.pnpm check\""],
    "assets.lint": ["\"assets.pnpm lint\""],
    "assets.format": ["\"assets.pnpm format\""],
    "assets.test": ["\"assets.pnpm test\""],
    "assets.test.coverage": ["\"assets.pnpm test:coverage\""],
    "assets.test.e2e": ["\"assets.pnpm test:e2e\""]
  ],
  deps: [
    "{:phoenix_vite, \"~> 0.5\"}",
    "{:phoenix_live_view, \"~> 1.0\"}",
    "{:live_svelte, \"~> 0.18\"}"
  ],
  files: [
    {"assets/.prettierignore", :sole_owner},
    {"assets/.prettierrc", :sole_owner},
    {"assets/css/app.css", :sole_owner},
    {"assets/css/theme.css", :sole_owner},
    {"assets/eslint.config.js", :sole_owner},
    {"assets/js/app.js", :sole_owner},
    {"assets/package.json", :sole_owner},
    {"assets/pnpm-lock.yaml", :sole_owner},
    {"assets/pnpm-workspace.yaml", :sole_owner},
    {"assets/svelte/components/AppShell.svelte", :sole_owner},
    {"assets/svelte/lib/sv5ui.js", :sole_owner},
    {"assets/test/svelte/components/AppShell.svelte.test.js", :sole_owner},
    {"assets/tsconfig.json", :sole_owner},
    {"assets/vite.config.mjs", :sole_owner},
    {"assets/vitest.config.js", :sole_owner},
    {"lib/mix/tasks/assets.pnpm.ex", :sole_owner},
    {"lib/APP/vite_watcher.ex", :sole_owner},
    {"lib/APP_web/components/core_components.ex", :sole_owner},
    {"lib/APP_web/components/layouts.ex", :sole_owner},
    {"lib/APP_web/components/layouts/root.html.heex", :sole_owner},
    {"test/mix/tasks/assets.pnpm_test.exs", :sole_owner},
    {"test/APP/vite_watcher_test.exs", :sole_owner},
    {"config/config.exs", :contributes, [key: :web_layer_config, at: :before_import]},
    {"config/dev.exs", :contributes, [key: :web_layer_dev]},
    {"lib/APP_web.ex", :manual,
     [
       after: ["", "  def static_paths, do: ~w(assets fonts images favicon.ico robots.txt)", ""],
       key: :web_layer_app_web
     ]},
    {"lib/APP_web/endpoint.ex", :manual,
     [
       after: [
         "  # When code reloading is disabled (e.g., in production),",
         "  # the `gzip` option is enabled to serve compressed",
         "  # static files generated by running `phx.digest`."
       ],
       key: :web_layer_endpoint
     ]},
    {"lib/APP_web/router.ex", :manual,
     [
       after: ["defmodule <%= @module %>Web.Router do", "  use <%= @module %>Web, :router", ""],
       key: :web_layer_router
     ]}
  ],
  name: :web_layer,
  version: "0.1.0"
}
